ruby-kid-master/config/routes.rb
KidsToys::Application.routes.draw do



  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'admin' => 'users/admin#index', :via => :get, :as => 'admin'
  match 'admin' => 'users/admin#login', :via => :post, :as => 'admin_login'
  match 'admin/users' => 'users/admin#users', :via => :get, :as => 'admin_users'
  match 'admin/update_user/:id' => 'users/admin#update_user', :via => [:put, :post], :as => 'admin_update_user'
  match 'admin/delete_user/:id' => 'users/admin#delete_user', :via => [:delete], :as => 'admin_delete_user'
  match 'admin/schools' => 'users/admin#schools', :via => :get, :as => 'admin_schools'
  match 'admin/notifications' => 'users/admin#notifications', :via => :get, :as => 'admin_notifications'
  match 'admin/logout' => 'users/admin#logout', :via => [:get, :delete], :as => 'admin_logout'

  match 'question_answers/update_all' => 'question_answers#update_all', via: [:put, :post], as: 'update_all_question_answers'
  resources :question_answers, except:[:show]

  resources :item_comments

  resources :cart_items, module: 'carts'

  match 'schools/admin' => 'schools#admin', :via => :get, :as => :schools_admin
  match 'schools/admin/:id' => 'schools#admin_edit', :via => :get, :as =>  :schools_admin_edit
  match 'schools/admin/:id' => 'schools#admin_update', :via => :post, :as => :schools_admin_update
  match 'schools/admin/:id' => 'schools#admin_destroy', :via=> :delete, :as => :schools_admin_destroy
  resources :schools, path: '/schools'

  match '/demo' => 'items#demo'

  namespace :inventory do
    resources :manager, :only => [:index] do

    end
    match 'activate' => 'manager#activate', as: 'activate_item'
    match 'approve' => 'manager#approve', as: 'approve_item'
    match 'deactivate' => 'manager#deactivate', as: 'deactivate_item'
    match 'decline' => 'manager#decline', as: 'decline_item'

    match 'item_for_approval' => 'manager#item_for_approval_notice', as: 'item_for_approval_notice'
  end


  match 'admin/categories' => 'categories#admin', :as => :admin_categories
  match 'categories/update_all' => 'categories#update_all', as: :update_all_categories, via:[:put, :post]
  resources :categories

  match 'category_groups/update_all' => 'category_groups#update_all', as: :update_all_category_groups, via:[:put, :post]
  match 'category_groups/:id/add_mapping' => 'category_groups#add_mapping', as: :add_category_group_mapping, via:[:put, :post]
  match 'category_groups/:id/add_curated_category' => 'category_groups#add_curated_category', as: :add_curated_category, via:[:put, :post]
  resources :category_groups
  resources :category_group_mappings, only: [:edit, :update]

  match 'categories/:id(/:title)' => 'categories#show', :as => :category_title
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'

ruby-kid-master/app/models/schools/child_care.rb
module Schools
  class ChildCare < School
    
  end
end

ruby-kid-master/app/models/schools/college.rb
module Schools
  class College < School
    
  end
end

ruby-kid-master/app/models/schools/private_grade_school.rb
module Schools
  class PrivateGradeSchool < School
    
  end
end

ruby-kid-master/app/models/schools/public_grade_school.rb
module Schools
  class PublicGradeSchool < School
    
  end
end

ruby-kid-master/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  skip_before_filter :verify_auth_user, only: [:index, :show, :new, :create]

  before_filter :check_permission, only: [:update, :destroy, :edit]
  before_filter :admin_set_schools, only: [:admin]

  # bc I'm not logging in everytime to test - AT
  # before_filter :verify_admin!, only: [:admin, :admin_show, :edit, :update, :destroy]
  
  # GET /schools
  # GET /schools.json

  def index
    # @schools = ::Schools::School.limit(50)
    @page_title = 'Schools'
    
    if params[:query].present?
      @page_title << ': ' + params[:query].strip
    end
    if params[:state].present?
      @page_title << ': ' + params[:state].strip + ' state'
    end
    if params[:zip].present?
      @page_title << " within zip-code #{params[:zip]}"
    end

    @schools_search = ::Schools::School.build_search(params)
    @schools_search.execute
    @schools = @schools_search.results
    unless request.xhr?
      @schools_gmap_hash = Gmaps4rails.build_markers(@schools) do |_school, marker|
        marker.lat _school.latitude
        marker.lng _school.longitude
        marker.title _school.name.titleize
        marker.infowindow _school.full_address
      end
    end

    respond_to do |format|
      format.js
      format.html{
        #for now, let's not keep it as a redirect to keep stupid people out.
        redirect_to root_path
      }
      format.json { render json: @schools }
    end
  end
    
  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = ::Schools::School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = ::Schools::School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = ::Schools::School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = ::Schools::School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_path(@school), notice: 'School was successfully created.' }
        format.json { render json: @school }
      else
        format.html { render action: "new" }
        format.json { render json: { errors: @school.errors.first.join(' '), success: false } }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = ::Schools::School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:schools])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = ::Schools::School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_path }
      format.json { head :no_content }
    end
  end

  # GET /schools/admin
  def admin
 
  end

  # GET /schools/admin/1
  # GET /schools/admin/1.json
  def admin_edit
      @school = ::Schools::School.find(params[:id])
     
      #find the next school to show for 'Skip'
      invalidated_schools = ::Schools::School.search_invalidated
      @next_school = invalidated_schools[(invalidated_schools.find_index(@school) + 1) % invalidated_schools.size]
      
      @num_students = Hash.new
      @num_students[@school.id] = ::Schools::SchoolGroup.student_count(@school)
      
      @nearby_schools = ::Schools::School.build_search(@school).execute.results
      @nearby_schools.each do |nearby_school|
          @num_students[nearby_school.id] = ::Schools::SchoolGroup.student_count(nearby_school)
      end

      @nearby_schools.sort_by! { |school| school.name }
  end

  # POST /schools/admin/:id
  def admin_update
     school_params = params[:school]
     school_params[:id] = params[:id]
     @school = ::Schools::School.find(school_params[:id])

     #find the next school to show after update
     invalidated_schools = ::Schools::School.search_invalidated
     @next_school = invalidated_schools[(invalidated_schools.find_index(@school) + 1) % invalidated_schools.size]

     unless school_params[:id].present? && school_params[:name].present? && school_params[:city].present? && school_params[:state].present? && school_params[:zip].present? && school_params[:country].present?
         return
     end

     zip_code = ::Geocode::ZipCode.search_by_zip_code(school_params[:zip] ).first
     
     if zip_code.nil?
        # either bad zip entered or not in zip_code table
     else
         school_params[:latitude] = zip_code.latitude
         school_params[:longitude] = zip_code.longitude
         school_params[:validated_admin] = true
         @school = ::Schools::School.find(school_params[:id])
         @school.update_attributes(school_params)
     end
    
     redirect_to schools_admin_edit_path(@next_school)
  end

  # DELETE /schools.admin/:id
  def admin_destroy

    if params[:school].nil?
        @users = ::User::User.where("current_school_id= #{params[:id]}") 
        @users.to_a.each do |user|
            user.update_attribute(:current_school_id, params[:nearby_school_id])
        end
    end
    
    @school = ::Schools::School.find(params[:id])
    
    invalidated_schools = ::Schools::School.search_invalidated
    @next_school = invalidated_schools[(invalidated_schools.find_index(@school) + 1) % invalidated_schools.size]
    
    @school.destroy
    redirect_to schools_admin_edit_path(@next_school)
  end 
  
  protected

  def check_permission
    if @school
      if auth_user.nil? || auth_user.is_a?(::Admin) == false
        flash[:error] = "You do not have permission to access this."
      end
    end

    if flash[:error].present?
      respond_to do |format|
        format.json { render( status: 401, json: make_json_status_hash(false) ) && return }
        format.html { redirect_to(schools_path) && return }
      end
    end
  end

  def admin_set_schools
      @schools = ::Schools::School.search_invalidated(params)
      @schools.paginate(:page => params[:page], :per_page => 20)
      @schools_students = Hash.new
      @schools.each do |school|
          @schools_students[school.id] = ::Schools::SchoolGroup.student_count(school) 
      end
  end
end

ruby-kid-master/app/helpers/schools/schools_helper.rb
module Schools
  module SchoolsHelper
  
    SORT_FIELDS = [['Relevancy', ''], ['Distance', 'LOCATION'],
                   ['School Name', 'NAME ASC'], ['Zip Code', 'ZIP ASC'] ]
    def self.valid_sort?(sort)
      SORT_FIELDS.collect { |ar| ar[1] }.include?(sort.to_s.upcase)
    end

  end
end

ruby-kid-master/app/views/schools/_form.html.erb
<div class='section-gap'>
</div>

<div class='center-block content-width row'>

  <%= form_for(@school, :url => (@school.new_record? ? schools_url : school_url(@school) ), html:{ name: 'school_form' } ) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% @school.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='col-sm-2'></div>
  <div class='col-sm-8'>
    <div class='form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, name:'school[name]', class:'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :address %>
      <%= f.text_field :address, name: 'school[address]', class:'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :city %>
      <%= f.text_field :city, name: 'school[city]', class:'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :state %>
      <%= f.text_field :state, name: 'school[state]', class:'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :zip %>
      <%= f.text_field :zip, name: 'school[zip]', class:'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :latitude %>
      <%= f.text_field :latitude, name: 'school[latitude]', class:'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :longitude %>
      <%= f.text_field :longitude, name: 'school[longitude]', class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit %>
    </div>

  </div>
  <div class='col-sm-2'></div>
  <% end %>

</div>

ruby-kid-master/app/views/schools/_nearby_schools_table.html.haml
- search_uri = 'http://www.google.com/search?q='
#schools_wrapper.full-width-block
  %ul#nearby_schools
    - @nearby_schools.each do|nearby_school|
      %li(class="nearby-school-item") 
        #{link_to nearby_school.name, schools_admin_destroy_path(:id => school.id, :nearby_school_id => nearby_school.id), {:method => :delete, :confirm => 'Are you sure you want to replace the school being edited?'}} <span style="color: red"> #{@num_students[nearby_school.id]} </span> 

ruby-kid-master/app/views/schools/admin.html.haml
- content_for(:head_extra) do
  :css
    .full-width-block { width:100%; margin:0; }
    #schools_wrapper {  max-height: 400px; overflow: scroll; padding:2px; background-color:#cccccc; }
    .schools-table { width:100%; margin:0; background-color:#ffffff; }
    .schools-table tr:hover td { background-color:rgb(213, 237, 253); }
    .schools-table td { padding: 5px 10px; }
    .schools-table td input { width:96%; border-radius: 4px; }
    #nearby_schools { list-style: none; margin: 0; padding:0; }
    #nearby_schools li { display:inline-block; margin:0 15px; width:45%; font-weight:300; line-height: 1.7em; }
    #nearby_schools li a { text-decoration:none; }

- content_for(:footer_extra) do
  :javascript
    jQuery(function(){
    });

.container
  .row(style="vertical-align:bottom; margin:0;")
    = form_for(:school, method: :get, remote:false ) do
      %img.pull-left(src="/assets/logos/kidstrade-title.png" alt="KIDSTrade" style="margin:0 2% 0 0;")
      %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
        %a(href='/admin') ADMIN
        %span.gray-title-color - SCHOOLS
      %p.pull-left(width="25%;")
        %input#school_name(type="text" name="q" value="#{params[:name]}" placeholder="Search Schools" width="80%;" )
          %button(type="submit"  aria-label="Search Schools" )
            %span.glyphicon.glyphicon-search(aria-hidden="true")/
      %p.pull-right.normal-weight.text-medium-title
        %a(href="#{schools_admin_path}") List
.full-width-block.subtle-inner-shadow
  %table.schools-table.table-striped
    %tbody
      %tr.gray-bottom-border
        %td.text-tiny.gray-title-color(width="30%") Name
        %td.text-tiny.gray-title-color(width="22%") City
        %td.text-tiny.gray-title-color(width="18%") State/Province/Region
        %td.text-tiny.gray-title-color(width="15%") Zip/Postal Code
        %td.text-tiny.gray-title-color(colspan="2" width="15%" ) Country
#schools_wrapper.full-width-block
  = render 'schools_table', :schools => @schools

ruby-kid-master/app/views/schools/admin_edit.html.haml
- search_uri = 'http://www.google.com/search?q='
- content_for(:head_extra) do
  :css
    .full-width-block { width:100%; margin:0; }
    #schools_wrapper {  max-height: 400px; overflow: scroll; padding:2px; background-color:#EFEFEF; }
    .schools-table { width:100%; margin:0; background-color:#ffffff; }
    .schools-table tr td { background-color:rgb(196, 232, 16); }
    .schools-table td { padding: 5px 10px; }
    .schools-table td input { width:96%; border-radius: 4px; }
    #nearby_schools { list-style: none; margin: 0; padding:0; }
    #nearby_schools li { display:inline-block; margin:0 15px; width:45%; font-weight:300; line-height: 1.7em; }
    #nearby_schools li a { text-decoration:none; }

- content_for(:footer_extra) do
  :javascript
    jQuery(function(){
    });

.container
  .row(style="vertical-align:bottom; margin:0;")
    = form_for(:school, method: :get, remote:false ) do
      %img.pull-left(src="/assets/logos/kidstrade-title.png" alt="KIDSTrade" style="margin:0 2% 0 0;")
      %p.pull-left.normal-weight.text-medium-title(style="margin:0 2% 0 0;")
        %a(href='/admin') ADMIN
        %span.gray-title-color - SCHOOLS
      %p.pull-left(width="25%;")
        %input#school_name(type="text" name="q" value="#{params[:name]}" placeholder="Search Schools" width="80%;" )
          %button(type="submit"  aria-label="Search Schools" )
            %span.glyphicon.glyphicon-search(aria-hidden="true")/
      %p.pull-right.normal-weight.text-medium-title
        %a(href="#{schools_admin_path}") List
        \-
        %a(href="#{schools_admin_edit_path(@next_school)}") Skip &gt;
.full-width-block.subtle-inner-shadow
  %table.schools-table.table-striped
    %tbody
      %tr.gray-bottom-border
        %td.text-tiny.gray-title-color(width="30%") Name
        %td.text-tiny.gray-title-color(width="22%") City
        %td.text-tiny.gray-title-color(width="18%") State/Province/Region
        %td.text-tiny.gray-title-color(width="15%") Zip/Postal Code
        %td.text-tiny.gray-title-color(colspan="2" width="15%" ) Country
#schools_wrapper.full-width-block
  %table.schools-table#admin-schools-table
    %tbody
      %tr 
        %td(width="30%") <span style="color: red"> #{@num_students[@school.id]} </span> #{link_to @school.name, search_uri + @school.name, :target => "_blank"}
        %td(width="22%") #{@school.city}
        %td(width="18%") #{@school.state}
        %td(width="15%") #{@school.zip}
        %td(colspan="2") #{@school.country}
#schools_add.full-width-block.form-group 
  = form_for(:school, remote:false) do|f| 
    %table.full-width-block
      %tbody 
        %tr 
          %td(width="30%") 
            = f.text_field(:name, class:'form-control', id: 'schools_add_name') 
          %td(width="22%") 
            = f.text_field(:city, class:'form-control', id: 'schools_add_city') 
          %td(width="18%") 
            = f.text_field(:state, class:'form-control', id:'schools_add_state') 
          %td(width="15%") 
            = f.text_field(:zip, class:'form-control', id: 'schools_add_zip') 
          %td(style="overflow:visible;") 
            = f.text_field(:country, class:'form-control', id: 'schools_add_country') 
          %td 
            %button.btn.btn-primary(type='submit' ) ADD
          %td
            = f.hidden_field(:id)
= form_for(:school, remote:false, method: :delete) do |f|
  %table.full-width-block
    %tbody
      %tr
        %td
          = f.hidden_field :replace, :value => "false"
          %button.btn.btn-danger DELETE
.full-width-block.gray-bottom-border
  .text-tiny.gray-title-color(style="padding-left: 1%;")
    Nearby Schools in Database
= render 'nearby_schools_table', :school => @school, :nearby_schools => @nearby_schools, :num_students => @num_students

ruby-kid-master/app/views/schools/index.html.erb
<style type="text/css">
  .striped-table td {
    padding: 10px; 
  }
  .striped-table tr:nth-child(even) {
    background-color: #eeeeee;
    
  }
</style>


<div class="row">

  <div class="col-sm-2">
  </div>

  <div class="col-sm-8">

    <h1>Found Schools</h1>

    <table class="striped-table">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Latitude, Longitude</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @schools.each do |school| %>
        <tr>
          <td><%= school.name %></td>
          <td><%= school.address %></td>
          <td><%= school.city %></td>
          <td><span title="<%= school.state_name %>"><%= school.state %></span></td>
          <td><%= school.zip %></td>
          <td><%= link_to "#{school.latitude}, #{school.longitude}", schools_path(lat: school.latitude, lon: school.longitude) %></td>
          <td><%= link_to 'Show', school_path(school) %></td>
          <td><%= link_to 'Edit', edit_school_path(school) %></td>
          <td><%= link_to 'Destroy', school_path(school), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>

    <br />

    <%= pagination_links(@schools) %>

    <br />

    <%= link_to 'New School', new_school_path, class: 'btn btn-default' %>

    <div class="clearfix">
      <br />
    </div>

    <%= render :partial => 'schools_gmap', locals:{ markers_hash: @schools_gmap_hash } %>

  </div>
  <div class="col-sm-2">

  </div>
</div>

ruby-kid-master/app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Address:</b>
  <%= @school.address %>
</p>

<p>
  <b>City:</b>
  <%= @school.city %>
</p>

<p>
  <b>State:</b>
  <%= @school.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @school.zip %>
</p>

<p>
  <b>Latitude:</b>
  <%= @school.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @school.longitude %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>