ruby-kid-master/config/routes.rb
KidsToys::Application.routes.draw do



  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'admin' => 'users/admin#index', :via => :get, :as => 'admin'
  match 'admin' => 'users/admin#login', :via => :post, :as => 'admin_login'
  match 'admin/users' => 'users/admin#users', :via => :get, :as => 'admin_users'
  match 'admin/update_user/:id' => 'users/admin#update_user', :via => [:put, :post], :as => 'admin_update_user'
  match 'admin/delete_user/:id' => 'users/admin#delete_user', :via => [:delete], :as => 'admin_delete_user'
  match 'admin/schools' => 'users/admin#schools', :via => :get, :as => 'admin_schools'
  match 'admin/notifications' => 'users/admin#notifications', :via => :get, :as => 'admin_notifications'
  match 'admin/logout' => 'users/admin#logout', :via => [:get, :delete], :as => 'admin_logout'

  match 'question_answers/update_all' => 'question_answers#update_all', via: [:put, :post], as: 'update_all_question_answers'
  resources :question_answers, except:[:show]

  resources :item_comments

  resources :cart_items, module: 'carts'

  match 'schools/admin' => 'schools#admin', :via => :get, :as => :schools_admin
  match 'schools/admin/:id' => 'schools#admin_edit', :via => :get, :as =>  :schools_admin_edit
  match 'schools/admin/:id' => 'schools#admin_update', :via => :post, :as => :schools_admin_update
  match 'schools/admin/:id' => 'schools#admin_destroy', :via=> :delete, :as => :schools_admin_destroy
  resources :schools, path: '/schools'

  match '/demo' => 'items#demo'

  namespace :inventory do
    resources :manager, :only => [:index] do

    end
    match 'activate' => 'manager#activate', as: 'activate_item'
    match 'approve' => 'manager#approve', as: 'approve_item'
    match 'deactivate' => 'manager#deactivate', as: 'deactivate_item'
    match 'decline' => 'manager#decline', as: 'decline_item'

    match 'item_for_approval' => 'manager#item_for_approval_notice', as: 'item_for_approval_notice'
  end


  match 'admin/categories' => 'categories#admin', :as => :admin_categories
  match 'categories/update_all' => 'categories#update_all', as: :update_all_categories, via:[:put, :post]
  resources :categories

  match 'category_groups/update_all' => 'category_groups#update_all', as: :update_all_category_groups, via:[:put, :post]
  match 'category_groups/:id/add_mapping' => 'category_groups#add_mapping', as: :add_category_group_mapping, via:[:put, :post]
  match 'category_groups/:id/add_curated_category' => 'category_groups#add_curated_category', as: :add_curated_category, via:[:put, :post]
  resources :category_groups
  resources :category_group_mappings, only: [:edit, :update]

  match 'categories/:id(/:title)' => 'categories#show', :as => :category_title
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'

ruby-kid-master/app/models/items/category_curated_item.rb
module Items
  class CategoryCuratedItem < ::ActiveRecord::Base

    attr_accessible :curated_category_id, :item_id, :category_id
    self.table_name = 'category_curated_items'

    belongs_to :category
    belongs_to :item
    belongs_to :curated_category

    ##
    # @params <Hash of Item attributes> :item_photos would be needed.
    # @return <Items::CategoryCuratedItem>
    def self.create_sample_item(curated_category_id, category_id, params = {})
      raise ::Exception.new("At least some item attributes are required") if params.blank?

      params[:description] = 'Sample item' if params[:description].blank?
      item_photos = params.delete(:item_photos)
      item = Item.new(params)
      item.user_id = ::Admin.cubbyshop_admin.id
      item.category_id = category_id
      item.price ||= 1.0
      logger.info " .. creating sample item.  valid? #{item.valid?}  #{item.errors.full_messages}"
      item.save
      item.load_item_photos_with_params({item_photos: item_photos})
      create(category_id: category_id, item_id: item.id, curated_category_id: curated_category_id)
    end

  end
end

ruby-kid-master/app/models/items/favorite_item.rb
module Items
  class FavoriteItem < ActiveRecord::Base

    attr_accessible :user_id, :item_id, :published, :created_at

    default_scope where(:published => true)

    belongs_to :user
    belongs_to :item

    after_create :create_notification!

    # @return <boolean> whether item is now in favorites
    def self.toggle_item_to_favorites(item_id, user_id)
      fav = where(item_id: item_id, user_id: user_id, published: true).last
      if fav
        fav.published = false
        fav.created_at = DateTime.now
        fav.save
        false
      else
        old_fav = where(item_id: item_id, user_id: user_id, published: false).last
        if old_fav #it was unliked recently.
          if old_fav.created_at > (DateTime.now - 1.week)
            old_fav.published = true
            old_fav.save
            true
          else
            old_fav.destroy
            create(item_id: item_id, user_id: user_id)
            true
          end
        else
          create(item_id: item_id, user_id: user_id)
          true
        end
      end
    end

    def self.add_item_to_favorites(item_id, user_id)
      unless where(item_id: item_id, user_id: user_id).present?
        create(item_id: item_id, user_id: user_id)
      end
    end

    ##
    # Generate a hash of number of users liking/favoring the items.
    # @item_ids <either Integer or Array> used as a parameter to query favorite items.
    # @which_buyer_id <Integer> optional; limit only to this buyer's
    # @return <Hash of item_id => integer>
    def self.make_favorite_counts_map(item_ids, which_buyer_id = nil)
      items = self.where(item_id: item_ids)
      items = items.where(user_id: which_buyer_id) if which_buyer_id
      fav_lists_map = items.group_by(&:item_id) # item_id => <Array>
      fav_counts_map = {}
      fav_lists_map.each_pair do|k, v|
        fav_counts_map[k] = v.size
      end
      fav_counts_map
    end

    ##
    # Sort by priorities: in favorites, item ID desc
    # @which_buyer_id <Integer> optional; limit only to this buyer's
    # @return <Hash of item_id => integer count users who set favorite item> same returned from make_favorite_counts_map
    def self.sort_items_by_favorite_counts!(items, which_buyer_id = nil)
      favorite_map = ::Items::FavoriteItem.make_favorite_counts_map(items.collect(&:id), which_buyer_id)
      items.sort! do|item_a, item_b|
        if favorite_map[item_a.id] && favorite_map[item_b.id].nil?
          -1
        elsif favorite_map[item_a.id].nil? && favorite_map[item_b.id]
          1
        else
          item_b.id <=> item_a.id
        end
      end
      favorite_map
    end

    def create_notification!
      return nil if item.nil?
      notification = ::Users::Notifications::LikeItem.create(sender_user_id: user_id, recipient_user_id: item.user_id,
                                   uri: Rails.application.routes.url_helpers.item_path(item),
                                   related_model_type: item.class.to_s, related_model_id: item.id
      )
      #UserMailer.favorite_item(self.item, self.user).deliver
      notification
    end

    private

  end
end

ruby-kid-master/app/models/items/item_search.rb
module Items
  class ItemSearch

    ###########################
    # Item Browse/Search

    ##
    # The maximum price of other items to collect into 1st set of items results.
    # @return <Float>
    def self.cutoff_of(original_price)
      price = original_price.round(2)
      if (0.01 .. 0.10).include?(price)
        price * 10.0
      elsif (0.11 .. 0.24).include?(price)
        price * 8.0
      elsif (0.25 .. 0.5).include?(price)
        price * 6.0
      elsif (0.51 .. 2.0).include?(price)
        price + 4.0
      elsif (2.01 .. 7.99).include?(price)
        price + 5.0
      elsif (8.0 .. 9.0).include?(price)
        price + 6.0
      else
        price * 1.5
      end
    end

    # @return <Array>, <Array>
    def self.sort_by_price_cutoff(items, price)
      within_list = [] # within the range of price up to cutoff
      outside_list = [] # under price or more than cutoff
      cutoff_price = cutoff_of(price)
      items.each do |item|
        if item.price <= cutoff_price
          within_list << item
        else
          outside_list << item
        end
      end
      within_list.sort! { |x, y| y.price <=> x.price } # descending
      outside_list.sort_by!(&:price)

      return within_list, outside_list
    end

  end
end

ruby-kid-master/app/views/items/_item_photo_form.html.haml
-# Required locals:
-#   item_photo_form <ActionView::Helpers::FormBuilder>
- item_photo = item_photo_form.object

%div(class="col-sm-#{item_photo.new_record? ? '8' : '4'}")
  .thumbnail
    = item_photo_form.text_field :name, :placeholder => 'Name (optional)', :class => 'form-control'
    - if item_photo.image.present? && item_photo.image_url.present?
      = hidden_field_tag('item_photo_ids[]', item_photo.id, id: "item_photo_#{item_photo.id}")
      = item_photo_form.hidden_field(:id)
      = link_to(item_photo.image_url, :target => '_blank') do
        = image_tag item_photo.image_url(:thumb).to_s, :title => item_photo.name, :class => 'img-responsive img-rounded'
    .caption
      
      - if item_photo.new_record?
        = item_photo_form.file_field :image
      - else
        %span(class='glyphicon glyphicon-remove')
        = link_to "Remove", "javascript:$('#item_photo_#{item_photo.id}').val(''); $('#item_photo_#{item_photo.id}').closest('.thumbnail').css('opacity', 0.2); void(0)"

ruby-kid-master/app/views/items/_item_thumbnail_collection.html.haml
-###############
-# Column-based layout for item thumbnails and later repositioned with Masonry plugin.
-# Reference: http://masonry.desandro.com
-# Required locals:
-#   items <Array of Item>
-# Optional locals:
-#   hide_user_label <Boolean> default false.
- 
  
%div(id='item-thumbnail-collection' class='center-block content-width js-masonry' data-masonry-options='{ "columnWidth": 150, "itemSelector": ".item" }')
  %div(id='columns')
  - items.each_with_index do|item, index|
    .pin
      = link_to(item_title_path(item, title:item.title_path) ) do
        = image_tag( default_thumbnail(item), title: item.title, alt: item.title)
      .caption
        .pull-left(style='font-size: 0.8em;')
          = user_name_label(item.user)
        .pull-right
          %span(style='font-size: 1.1em;') #{price_display(item.price) }
        - if item.user.current_school_id && item.current_school
          .clearfix
          .pull-left
            %span.gray-title-color #{item.current_school.name}
        .clearfix

ruby-kid-master/app/views/items/_item_thumbnails.html.haml
-###############
-# Required locals:
-#   items <Array of Item>
-# Optional locals:
-#   hide_user_label <Boolean> default false.
-

%div(id='thumbnail-columns')
  - items.each_with_index do|item, index|
    %figure
      = link_to(item_title_path(item, title:item.title_path) ) do
        = image_tag( default_thumbnail(item), title: item.title, alt: item.title)
      %figcaption
        %span.pricespan #{price_display(item.price) }
        - if item.user.current_school_id && item.current_school
          %small #{item.current_school.name}
        .clearfix

ruby-kid-master/app/views/items/_items_search_head.html.haml
-##
-# Additional header CSS and Javascript for item browsing.

- content_for(:head_extra) do

  = javascript_include_tag 'items'

- content_for(:footer_extra) do

  :javascript

    apiURL = "#{items_path( current_search_params.merge(format: 'js') )}";
    page = #{[params[:page].to_i, 1].max };
      
    $(function () {


      $("#items_search_sort").change( function() { $("#items_search_form").submit(); } );

      $(window).load( setTilesWithWookmark );
      $(window).resize( setTilesWithWookmark );
      
      $(document).bind('scroll', onScroll);
      
    } );

ruby-kid-master/app/views/items/_manage_item_bar.html.haml
- content_for(:head_extra) do

  :css
    body {
      padding-bottom: 100px;
    }
    .navbar-table td {
      width: 25%;
      padding: 10px 5px;
    }

    .tab-link {
      width: 80px;
      height: 80px;
    }
    .tab-link img {
      max-height: 80px;
    }

    .tab-edit { background: url('/assets/nav/edit@2x.png') no-repeat center; }
    .tab-share { background: url('/assets/nav/share@2x.png') no-repeat center; }
    .tab-print { background: url('/assets/nav/print@2x.png') no-repeat center; }
    .tab-end { background: url('/assets/nav/end@2x.png') no-repeat center; }

    @media only screen and (max-width: 600px)  {
      .tab-link {
        width: 40px;
        height: 40px;
      }
      .tab-link img {
        max-height: 40px;
      }
      .tab-edit { background: url('/assets/nav/edit@2x.png') no-repeat center; }
      .tab-share { background: url('/assets/nav/share@2x.png') no-repeat center; }
      .tab-print { background: url('/assets/nav/print@2x.png') no-repeat center; }
      .tab-end { background: url('/assets/nav/end@2x.png') no-repeat center; }
    }


%nav(class="navbar navbar-default navbar-fixed-bottom" style='background-color:white; z-index:6000;')
  .full-separator
  %div(class='container content-width')
    %table(style='width: 100%' class='navbar-table')
      %tbody
        %tr
          %td.text-center
            %a(class='tab-link' href="#{edit_item_path(item)}" title="Edit Item")
              %img(src="/assets/nav/edit@2x.png" alt="Edit Iem")
          %td.text-center
            %a(class='tab-link' href="" title="Share Item")
              %img(src="/assets/nav/share@2x.png" alt="Share Item")
          %td.text-center
            %a(class='tab-link' href="" title="Print Item")
              %img(src="/assets/nav/print@2x.png" alt="Print Item")
          %td.text-center
            = link_to(item_path(item), method:'delete', remote:true, class:'tab-link', title:'Delete/End Item', confirm: t('selling.end_item.confirm') ) do
              %img(src="/assets/nav/end@2x.png" alt="Delete/End Item")

ruby-kid-master/app/views/items/edit.html.haml
%div(class='center-block' style="padding: 0 5%")

  .section-gap

  = render 'form'

  %nav
    %ul.pager
      %li
        = link_to inventory_manager_index_path(tab: auth_user.is_a?(Parent) ? 'inactive' : '')  do
          &larr; Back to #{@item.user.display_name}&rsquo;s Items
      %li
        = link_to 'Reset & Show Item Again'

  .clearfix
    %p

ruby-kid-master/app/views/items/index.html.haml
.section-gap

= render(partial: 'items/items_search_head')

%div(class='container')
  
  .row(style="display: none;")
    %ol.breadcrumb
      %li
        = link_to('For Sale Items', items_path)
      - if @category
        %li
          = link_to(@category.name, category_title_path(@category, title: @category.title_path) )
      - if params[:query].present?
        %li(class='active')
          %strong.text-success &ldquo;#{params[:query]}&rdquo;

  %div(class='row content-width' style="display: none;")
    %div(class='col-sm-offset-8 col-sm-4 text-right')
      = form_tag({}, :method => 'get', :id => 'items_search_form') do
        Sort by:
        = select_tag(:sort, sort_select_options(params[:sort] ), :id => 'items_search_sort' )

  = section_tabs(css_class: 'content-width center-block')

  .section-gap

  %div(id='items_container' class='row content-width center-block')
    %ul(id="tiles")
      - (@items || @items_search.results).each do|item|
        %li
          = render(partial: 'items/item_thumbnail', locals:{ item: item, favorite_item_ids: @favorite_item_ids } )

    .clearfix

  %div(id="loader-circle" class='row content-width center-block')
    %span(class='vertical-center') Loading ...

  -# = pagination_links (@items || @items_search.results), { is_active: true }

  .row
    %p.clearfix
  
  - if auth_user && auth_user.is_a?(Child)
    = render(partial: 'home/bottom_tabbar')

ruby-kid-master/app/views/items/show.html.haml
- content_for(:head_extra) do

  = stylesheet_link_tag 'trade-ui'

  = javascript_include_tag 'items'

- content_for(:footer_extra) do

  :javascript
    var priceTagTopSpace = 10, priceTagWidth = 60;
    
    function onScroll(event) {
      repositionPriceTag();
    }
    function onWindowResize(event) {
      priceTagWidth = $(".price-tag:first").width();
      repositionPriceTag();
    }
    
    function repositionPriceTag() 
    {
      var scrollTop = $(window).scrollTop();
      var priceTag = $(".price-tag:first");
      var list = $("img.main-image-placeholder");
      var firstPicture = $("img.main-image-placeholder:first");
      var firstPictureBottom = firstPicture.offset().top + firstPicture.height();
      var picturesWrapper = $("#pictures_wrapper");
      var picturesOffset = picturesWrapper.offset();
      var picturesWrapperBottom = picturesOffset.top + picturesWrapper.height();
      var spaceAboveBottom = priceTag.height() * 1.5;

      if ( scrollTop > picturesWrapperBottom - spaceAboveBottom ) {
        priceTag.offset( { top: picturesWrapperBottom - spaceAboveBottom } );
      }
      else if ( scrollTop > firstPictureBottom - spaceAboveBottom + priceTagTopSpace ) // push below 1st picture
      {
        priceTag.offset( { top: scrollTop + priceTagTopSpace } );
      }
      else {
        //priceTag.offset( { left: firstPicture.offset().left + firstPicture.width() - priceTagWidth, top: firstPicture.offset().top + priceTagTopSpace } );
        priceTag.offset( { top: firstPictureBottom - spaceAboveBottom } );
      }
    }

    jQuery(function() {
      $(".link_with_tip").tooltip({animation: false, placement:'auto'} );

      $(window).load( setTilesWithWookmark );
      $(window).resize( setTilesWithWookmark );

      $(".price-tag:first").css("display", "block");
      priceTagWidth = $(".price-tag:first").width();
      repositionPriceTag();
      $(document).bind('scroll', onScroll);
      $(window).bind('resize', onWindowResize);
    } );

- if auth_user.try(:id) != @item.user_id
  = render(partial: 'users/seller_info', locals: { user: @item.user } )
- else
  .no-seller-info-space &nbsp;

- if (auth_user && auth_user.parent_of?(@item.user) )
  .full-separator

%div(id='item-content-wrapper' class='container row content-width center-block')
  - if @item.item_photos.present? && (auth_user.nil? || !auth_user.parent_of?(@item.user) )
    = render(partial: 'items/item_photos_in_stack', locals: { item: @item, is_in_favorite_items: @is_in_favorite_items } )

  %div(class='container' style='padding: 10px 0; display: inline;')
    %p(class='text-moderate-big-title dark-title-color')
      = html_escape( @item.description ).strip

%div(class='container row content-width center-block')
  - if @item.tradeable_to_user?(auth_user)
    %div(id="actions-wrapper" class='row')
      %a(href="#{new_trade_path(item_id: @item.id )}" class='btn btn-lg large-form-button trade-button') Trade
      %a(href="#{new_item_comment_path(item_id: @item.id)}" class='btn btn-lg large-form-button ask-question-button') Ask Question
      = link_to('Add to Cart', carts_add_path(item_id: @item.id), id:"add_to_cart_#{@item.id}", |
        class: 'btn btn-lg large-form-button add-to-cart-button', role: 'button', remote: true, method: 'post') |

  - if @item.manageable_by_user?(auth_user)
    %div(class='bottom-spaced text-superbig-title normal-weight gray-title-color')
      = gender_group_icons(@item.gender_group)
      &nbsp;
      %span(style='vertical-align: bottom;')
        #{::Users::AgeGroup.age_group_name(@item.age_group) } #{Category.find_by_id(@item.category_id).try(:name)}
        - if auth_user.is_a?(Parent)
          = @item.category.try(:name)
    .no-seller-info-space

  - if @item.item_photos.present? && (auth_user && auth_user.parent_of?(@item.user) )
    = render(partial: 'items/item_photos_in_stack', locals: { item: @item, is_in_favorite_items: @is_in_favorite_items } )

- if @other_items.present?
  .full-separator(style='margin-top: 20px;')
  %div(class='row content-width center-block' style='padding: 10px;')
    %div(class='pull-left text-moderate-big-title male-color')
      %strong #{@item.user.display_name}'s Other Items
    %div(class='pull-right male-color text-right')
      %a(href="#{new_report_path(item_id: @item.id)}")
        %img.report-item-icon(src='/assets/items/report@2x.png' alt="#{t('item.action.report_item')}")
    .clearfix

  %div(id='items_container' class='row content-width center-block')
    = render(partial: 'items/item_thumbnail_grid', locals:{ items: @other_items, hide_user_label:true, hide_school_teacher_label:true, favorite_item_ids: @favorite_item_ids  } )

.section-gap
.row
  .col-md-6
    - if has_questions_and_offers?(@item)
      %div(class='panel panel-info')
        .panel-heading
          %a(name='qo')
          %h4 Questions and Offers
        - if (item_comments = @item.item_comments.still_open).present?
          .panel-body(id="itemCommentsTable")
            = render(partial: 'item_comments/table', locals:{ item: @item, item_comments: item_comments } )

- if auth_user && @item.manageable_by_user?(auth_user)
  = render(partial: 'items/manage_item_bar', locals: { item: @item } )