ruby-kid-master/config/routes.rb
KidsToys::Application.routes.draw do



  use_doorkeeper

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match 'admin' => 'users/admin#index', :via => :get, :as => 'admin'
  match 'admin' => 'users/admin#login', :via => :post, :as => 'admin_login'
  match 'admin/users' => 'users/admin#users', :via => :get, :as => 'admin_users'
  match 'admin/update_user/:id' => 'users/admin#update_user', :via => [:put, :post], :as => 'admin_update_user'
  match 'admin/delete_user/:id' => 'users/admin#delete_user', :via => [:delete], :as => 'admin_delete_user'
  match 'admin/schools' => 'users/admin#schools', :via => :get, :as => 'admin_schools'
  match 'admin/notifications' => 'users/admin#notifications', :via => :get, :as => 'admin_notifications'
  match 'admin/logout' => 'users/admin#logout', :via => [:get, :delete], :as => 'admin_logout'

  match 'question_answers/update_all' => 'question_answers#update_all', via: [:put, :post], as: 'update_all_question_answers'
  resources :question_answers, except:[:show]

  resources :item_comments

  resources :cart_items, module: 'carts'

  match 'schools/admin' => 'schools#admin', :via => :get, :as => :schools_admin
  match 'schools/admin/:id' => 'schools#admin_edit', :via => :get, :as =>  :schools_admin_edit
  match 'schools/admin/:id' => 'schools#admin_update', :via => :post, :as => :schools_admin_update
  match 'schools/admin/:id' => 'schools#admin_destroy', :via=> :delete, :as => :schools_admin_destroy
  resources :schools, path: '/schools'

  match '/demo' => 'items#demo'

  namespace :inventory do
    resources :manager, :only => [:index] do

    end
    match 'activate' => 'manager#activate', as: 'activate_item'
    match 'approve' => 'manager#approve', as: 'approve_item'
    match 'deactivate' => 'manager#deactivate', as: 'deactivate_item'
    match 'decline' => 'manager#decline', as: 'decline_item'

    match 'item_for_approval' => 'manager#item_for_approval_notice', as: 'item_for_approval_notice'
  end


  match 'admin/categories' => 'categories#admin', :as => :admin_categories
  match 'categories/update_all' => 'categories#update_all', as: :update_all_categories, via:[:put, :post]
  resources :categories

  match 'category_groups/update_all' => 'category_groups#update_all', as: :update_all_category_groups, via:[:put, :post]
  match 'category_groups/:id/add_mapping' => 'category_groups#add_mapping', as: :add_category_group_mapping, via:[:put, :post]
  match 'category_groups/:id/add_curated_category' => 'category_groups#add_curated_category', as: :add_curated_category, via:[:put, :post]
  resources :category_groups
  resources :category_group_mappings, only: [:edit, :update]

  match 'categories/:id(/:title)' => 'categories#show', :as => :category_title
  match 'user_categories' => 'categories#user_categories', :as => :user_categories

  get 'account/confirm' => 'account_confirmation#index', as: :account_confirmation
  get 'account/credit_card' => 'account_confirmation#credit_card', as: :account_credit_card
  get 'account/driver_license' => 'account_confirmation#driver_license', as: :account_driver_license
  post 'account/driver_license' => 'account_confirmation#upload_driver_license', as: :account_upload_driver_license
  post 'account/confirm/payment' => 'account_confirmation#authorize_payment', as: :account_confirmation_payment
  get 'account/confirmed' => 'account_confirmation#account_confirmed', as: :account_confirmed
  #####################
  # Trade

  resources :trades, module: 'trading', except: [:edit, :update, :create], as: 'trade'
  match 'trades/(:id)(.:format)' => 'trading/trades#create', as: 'create_trade', via: :post
  match 'trades/(:id)(.:format)' => 'trading/trades#reply', as: 'reply_trade', via: :put
  match 'trades/:id/comments(.:format)' => 'trading/trades#list_comments', as: 'trade_comments', via: :get
  match 'trades/:id/comments(.:format)' => 'trading/trades#comments', as: 'create_trade_comments', via: :post
  match 'trades/:id/accept(.:format)' => 'trading/trades#accept', as: 'accept_trade', via: :post
  match 'trades/:id/decline(.:format)' => 'trading/trades#decline', as: 'decline_trade', via: :delete
  match 'trades/:id/cancel(.:format)' => 'trading/trades#destroy', as: 'cancel_trade', via: [:put, :post, :delete]
  match 'trades/:id/pick_meeting(.:format)' => 'trading/trades#pick_meeting', as: 'pick_meeting', via: [:put, :post]
  match 'trades/:id/respond_to_meeting(.:format)' => 'trading/trades#respond_to_meeting', as: 'respond_to_meeting', via: [:put, :post]
  match 'trades/:id/confirm(.:format)' => 'trading/trades#confirm_completion', as: 'confirm_completion', via: [:put, :post]
  match 'trades/:id/pack(.:format)' => 'trading/trades#confirm_packed', as: 'confirm_packed', via: [:put, :post]
  match 'trades/:id/completed(.:format)' => 'trading/trades#completed', as: 'completed_change', via: [:put, :post]

  resources :buy_requests, module: 'trading', only: [:new, :create, :show]
  match 'buy_requests/(:id)/accept(.:format)' => 'trading/buy_requests#accept', as: 'accept_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/decline(.:format)' => 'trading/buy_requests#decline', as: 'decline_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/confirm(.:format)' => 'trading/buy_requests#confirm', as: 'confirm_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/sold(.:format)' => 'trading/buy_requests#sold', as: 'sold_buy_request', via: [:put, :post]
  match 'buy_requests/(:id)/not_sold(.:format)' => 'trading/buy_requests#not_sold', as: 'not_sold_buy_request', via: [:put, :post]

  #####################
  # Notifications

  resources :notifications, module: 'users', only: [:index, :show] do
    member do
      delete 'delete'
    end
  end
  match 'notifications/archive' => 'users/notifications#archive', as: 'archive_notifications', via: :put
  match '/notifications/push' => 'users/notifications#send_push_notification', as: 'send_push_notification', via: [:put, :post]
  match '/notifications_count(.:format)' => 'users/notifications#count', as: 'notifications_count', via: :get

  root :to => 'home#home'
  get "/home/:version" => "home#home"
  get "/terms" => "home#terms"
  get "/privacy" => "home#privacy"
  get "/privacy_and_terms" => "home#privacy_and_terms"
  get "/safety" => "home#safety"
  get "/about_us" => "home#about_us"
  get "/faq" => "home#faq"

  match 'tips/update_all' => 'tips#update_all', via: [:put, :post], as: 'update_all_tips'
  resources :tips, except: [:show]

  #####################
  # User

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {registrations: 'users', sessions: 'sessions', passwords: 'passwords'}
  devise_scope :user do
    post '/forgot_password', to: 'passwords#create'
    get '/users/password/edit', to: 'password#edit'
    put '/users/password', to: 'passwords#update'
  end
  #post '/forgot_password' => 'devise/passwords#create'
  #get '/forgot_password'=> 'devise/passwords#edit'

  # Custom routes that still use :users scope
  devise_scope :user do
    get "/users/logout" => "sessions#destroy"
    get "/users/show_current_user", as: "show_current_user"
    get "/users/dashboard", to: "users#dashboard", as: "users_dashboard"
    get "/users/friends", to: "users#friends", as: "users_friends"
    get "/users/:id/items", to: "stores#show", as: "users_items"

    get "/users/children", to: "users/children#index", as: "users_children"
    get "/users/child", to: "users/children#new", as: "users_new_child"
    match '/users/child/:id/school' => 'users/children#school', as: 'child_school', via:[:get]
    match '/users/child/:id/update_school' => 'users/children#update_school', as: 'child_update_school', via:[:put, :post]
    get "/users/child/:id", to: "users/children#edit", as: "users_edit_child"
    post "/users/child/create", to: "users/children#create", as: "users_create_child"
    post '/users/student/create', to: 'users/children#create_student', as: 'users_create_student'
    post "/users/push_notifications", to: "users/user_notification_tokens#create", as: "create_user_notification_tokens"
    post "/users/child/login", to: "users/children#login", as: "users_login_child"
    put "/users/child/:id", to: "users/children#update", as: "users_update_child"
    post "/users/sign_in_as/:id", to: "sessions#sign_in_as", as: "sign_in_as"

    get "/users/:id", to: "users#show", as: "user"
    put "/users/login(.format)", to: "sessions#new"
    put "/users" => "users#update", as: "update_user"

    get '/boundaries', to: 'users/boundaries#index', as: 'boundaries'
    put '/boundaries', to: 'users/boundaries#update', as: 'update_boundaries'

    get  '/users/potential_friends' => 'users/friend_request#index', as: 'potential_friends'
    get '/friend_request/:id' => 'users/friend_request#show', as: 'friend_request'
    post '/friend_request' => 'users/friend_request#create', as: 'create_friend_request'
    match '/friend_request/:id/accept' => 'users/friend_request#accept', as: 'accept_friend_request', via:[:put, :post]
    match '/friend_request/:id/decline' => 'users/friend_request#deny_request', as: 'deny_friend_request', via:[:put, :post]

    # Users APIs
    scope path: '/api/v1' do
      get '/users/followings', to: 'users#followings', as: 'api_get_followings'
      get '/videos/value_prop' => 'sessions#video', via: [:get]
      match '/users/logout' => 'sessions#destroy', via: [:get, :put, :delete], as: 'api_users_logout'

      get  '/users/potential_friends' => 'users/friend_request#index', as: 'api_get_potential_friends'
      post '/users/friend_request' => 'users/friend_request#create', as: 'api_create_friend_request'
      get '/users/friend_request/:id' => 'users/friend_request#show', as: 'api_show_friend_request'
      post '/users/friend_request/:id/accept' => 'users/friend_request#accept', as: 'api_accept_friend_request'

ruby-kid-master/app/models/users/age_group.rb
module Users
  class AgeGroup
    attr_accessor :name, :range

    def initialize(attributes = {})
      self.name = attributes[:name]
      self.range = attributes[:range]
    end

    AGE_GROUPS = [
        AgeGroup.new(name: 'Infant', range: 0 .. 1),
        AgeGroup.new(name: 'Toddler', range: 2 .. 4),
        AgeGroup.new(name: 'Youth', range: 5 .. 10),
        AgeGroup.new(name: 'Teen', range: 11 .. 17)
        #AgeGroup.new(name: 'Young Adult', range: 18 .. 29),
        #AgeGroup.new(name: 'Mid-age Adult', range: 30 .. 59),
        #AgeGroup.new(name: 'Senior', range: 60 .. 150)
    ]


    def self.matching_age_group(age_or_birthdate)
      age = age_or_birthdate.is_a?(Date) ? ((Date.today - age_or_birthdate) / 365.25).to_i : age_or_birthdate.to_i
      group = AGE_GROUPS.find { |g| g.range.include?(age) }
      group ||= AGE_GROUPS.last
      group
    end
    
    ##
    # @return <String> either in numeric range like '1 - 3' or partially worded like '2 & Under'
    def self.age_group_name(age_group)
      age_group = '' if age_group.blank?
      if age_group == '0-1'
        '2 & Under'
      elsif age_group =~ /^(\d+)\s*\-\s*$/
        "#{$1} & Up"
      elsif age_group =~ /^(\d+)\s*\-\s*(\d+)$/
        ( $1.to_i == 0 ) ? "#{$2} & Under" : "#{$1} - #{$2}"
      else
        'All Ages'
      end
    end
    
    # Instead of name, generates the range in words like '2 to 4'
    def self.range_in_words(range)
      if range == (0 .. 1)
        'Under 1'
      elsif range.begin == 60
        '60 or Older'
      else
        "#{range.begin} to #{range.end}"
      end
    end

    # intended_age_group <String>
    # return <Integer> could be nil, meaning all ages
    def self.intended_age_group_to_difference(intended_age_group)
      intended_ag = intended_age_group.to_s.downcase # normalize
      age_group_diff = nil
      if intended_ag == 'same'
        age_group_diff = 0
      elsif intended_ag == 'younger'
        age_group_diff = -1
      elsif intended_ag == 'older'
        age_group_diff = 1
      end
      age_group_diff
    end

    # return <integer> could be nil
=begin
    def self.intended_age_group_to_age_group(current_user, intended_age_group)
      age_group = nil
      if (age_group_diff = intended_age_group_to_difference(intended_age_group) )
        relative_ag_index = nil
        AGE_GROUPS.each_with_index do|ag, index|
          if ag.range.include?( current_user.age ) ######### actually there's no user.age cuz that'd need standardized mapping of grade to age
            relative_ag_index = index + age_group_diff
          end
        end
        if relative_ag_index && relative_ag_index >= 0 && relative_ag_index < AGE_GROUPS.size
          age_group = AGE_GROUPS[relative_ag_index]
        end
      end
      age_group
    end
=end

    ##
    # return <Array of AgeGroup>
    def self.make_relative_age_groups(age)

    end
  end
end

ruby-kid-master/app/models/users/boundary.rb
module Users
  class Boundary < ActiveRecord::Base
    
    attr_accessible :type, :user_id, :content_type_id, :content_keyword

    belongs_to :user, class_name: '::User'

    CACHE_EXPIRATION_LENGTH = 6.hours.to_i

    scope :child_circle_options, conditions: { type: 'Users::ChildCircleOption' }
    scope :user_blocks, conditions: { type: 'Users::UserBlock' }
    scope :keyword_blocks, conditions: { type: 'Users::KeywordBlock' }
    scope :category_blocks, conditions: { type: 'Users::CategoryBlock' }

    ##
    # Draft version.  Should be implemented in subclass where the record type is defined.
    def content_record
      nil
    end

    # Should be implemented in subclass where the record type is defined
    def self.content_value_column
      'content_type_id'
    end

    def content_value
      self.attributes[self.class.content_value_column]
    end

    def as_json(options = {})
      h = super(options.merge(only: [:id, :type, :user_id, :created_at] ) )
      h[:content_value] = self.content_value
      h
    end


    ##
    # type_class <SubClass of Boundary>
    # ids <Array of either all integer ids or all String keywords>
    # @return <Array of Boundary created>
    def self.add!(user_id, type_class, ids)
      return [] if ids.blank?

      # Invalidate cache
      expire_boundaries!(user_id)

      list = []
      if type_class.content_value_column == :content_keyword
        ids.each do|id|
          list << type_class.create(user_id: user_id, content_keyword: id.to_s) if id.to_s.present?
        end
      else
        ids.each do|id|
          list << type_class.create(user_id: user_id, content_type_id: id)
        end
      end
      list
    end

    ##
    # type_class <Class>
    # ids <Array of either all integer ids or all String keywords>

    def self.remove!(user_id, type_class, ids)

      expire_boundaries!(user_id)

      if ids_to_block.first.is_a?(String)
        delete_all(user_id: user_id, type: type_class.to_s, content_keyword: ids)
      else
        delete_all(user_id: user_id, type: type_class.to_s, content_type_id: ids)
      end
    end

    ##
    # @return <Array of JSON values, each of which is the hash of the Boundary object>
    def self.get_boundaries(user_id, use_cache = true)
      cache_key = make_cache_key(user_id)
      result = if use_cache
                 res = $redis.get(cache_key).to_s
                 # logger.info "| Get cache? #{use_cache} ... user_blocks of #{user_id} => #{res} |"
                 res.present? ? JSON.parse(res) : nil
               else
                 nil
               end

      unless result
        result = where(user_id: user_id)

        $redis.set cache_key, result.to_json
        $redis.expire cache_key, CACHE_EXPIRATION_LENGTH
      end
      result
    end

    def self.expire_boundaries!(user_id)
      logger.info "| Expiring ... user_blocks of #{user_id}"
      $redis.del make_cache_key(user_id)
    end

    ##
    # Exact values of just this type
    def self.get_content_values(user_id, boundary_class, use_cache = true)
      values = []
      get_boundaries(user_id, use_cache).each do|b|
        if b.is_a?(boundary_class)
          values << b.content_value
        end
      end
      values
    end

    ##
    # blist <Array of Boundary or Integer or String>
    def self.extract_content_values_from_list(blist)
      blist.collect {|b| b.is_a?(::Users::Boundary) ? b.content_value : b }
    end


    protected

    def self.make_cache_key(user_id)
      "boundaries/#{user_id}"
    end


  end
end

ruby-kid-master/app/models/users/category_block.rb
module Users
  class CategoryBlock < Boundary

    self.table_name = 'boundaries'

    alias_attribute :blocker_user_id, :user_id
    alias_attribute :category_id, :content_type_id
    
    belongs_to :category, class_name: '::Category', foreign_key: 'content_type_id'    

    def content_record
      category
    end

  end
end

ruby-kid-master/app/models/users/child_circle_option.rb
module Users
  class ChildCircleOption < Boundary

    CIRCLE_OPTIONS_MAP = ::ActiveSupport::OrderedHash.new
    CIRCLE_OPTIONS_MAP['ONE_GRADE_AROUND'] = '+/- A Grade'
    CIRCLE_OPTIONS_MAP['GRADE_ONLY'] = 'Grade Only'
    CIRCLE_OPTIONS_MAP['CLASS_ONLY'] = 'Class Only'

    def content_record
      content_keyword
    end

    def self.content_value_column
      'content_keyword'
    end

  end
end

ruby-kid-master/app/models/users/keyword_block.rb
module Users
  class KeywordBlock < Boundary

    alias_attribute :blocker_user_id, :user_id

    def content_record
      content_keyword
    end

    def self.content_value_column
      'content_keyword'
    end

  end
end

ruby-kid-master/app/models/users/notifications/basic.rb
##
# Default type.
module Users
  module Notifications
    class Basic < ::Users::Notification

      def copy_identifier
      	:trade_basic
      end

      def get_type
      	:social
      end

    end
  end
end

ruby-kid-master/app/views/users/_edit_profile_for_parent.html.haml
-# Optional inner content_for content
-#   :other_tab_content - displayed at the end of the tab-content. Intended to use for Address tab

.clearfix
.section-gap

%ul(class='nav nav-tabs' id='profile_nav_tabs')
  %li(class="#{profile_tab_css_class('parent')}")
    %a.navbar-brand(href="#{edit_user_registration_path}") Parent Profile
    
  %li(class="#{profile_tab_css_class('children')}")
    %a.navbar-brand(href="#{edit_user_registration_path(tab:'children')}") Children
  
  %li(class="#{profile_tab_css_class('address')}")
    %a.navbar-brand(href="#{user_locations_path}") Addresses
    
  %li(class="#{profile_tab_css_class('phone')}")
    %a.navbar-brand(href="#{user_phones_path}") Phone Numbers



%div(class='tab-content')
  %div(class="tab-pane panel-no-top-border #{profile_tab_css_class('parent')}" id='parent_tab')
    = render partial:'devise/registrations/form_for_parent', locals:{}
    
  %div(class="tab-pane panel-no-top-border #{profile_tab_css_class('children')}" id='children_tab')
    = render(:partial => '/users/children/children_panel')
  
  = yield(:other_tab_content)

ruby-kid-master/app/views/users/_schools_data.html.haml
- content_for(:footer_extra) do

  :javascript
    var schoolNames = #{@schools.to_a.collect{|sc| {'label' => "#{sc.name.titleize} (#{sc.address})", 'value'=> sc.id } }.to_json };
          
    jQuery(function() {
        
      $('#search_schools_name').autocomplete( {
          source: schoolNames,
          minLength: 2,
          select: function(event, ui) {
            $("#user_current_school_id").attr("value", ui.item.value);
          }
        } 
      );
      
      $('#search_schools_button').click( function(event) {
          $.ajax("/schools?state=" + $("#search_schools_state").val() + "&zip=" + $("#search_schools_zip").val() );
        }
      );
          
      $("#search_schools_state").change(function(event) { 
          $.ajax("/schools?state=" + event.target.options[event.target.selectedIndex].value); 
        } 
      );
      $("#search_schools_zip").blur(function(event) {
          if(event.target.value != "") {
            $.ajax("/schools?zip=" + event.target.value );
          }
        }
      );
    } );

ruby-kid-master/app/views/users/_seller_info.html.haml
-# Required locals:
-#  user <User>
-# Optional locals:
-#  hide_user_avatar <boolean> default false.
-#  show_trade_icon <boolean> default false.  Intentionally show trade icon regardless of the viewer
-#  show_child_name <boolean> default false.
:ruby
  hide_user_avatar = false if not defined?(hide_user_avatar)
  show_trade_icon = false if not defined?(show_trade_icon)
  show_child_name = false if not defined?(show_child_name)

%div(class='row container center-block content-width')
  - unless hide_user_avatar
    %div(class='user-avatar-wrapper pull-left')
      .user-avatar-circle
        %a(href="#{store_path(user)}")
          %img.user-avatar-icon.vertical-center(src="#{user.profile_image_url(:thumb)}" alt="#{user.display_name}" title="#{user.display_name}")

  %div(class='pull-left')
    %a(href="#{store_path(user)}")
      = user_name_label(user, :span)
    - if show_child_name
      = " - #{user.first_name.titleize}"
    %br
    - if user.teacher.present? || user.current_school
      %span(class='text-big-title dark-title-color') #{user.teacher.present? ? user.teacher : user.current_school.name}
      %br
    %span(class='text-moderate-big-title gray-title-color') #{grade_and_item_count_label(user) }
  %div(class='pull-right vertical-center')
    - if auth_user && user.id != auth_user.try(:id) && !auth_user.is_a?(Parent)
      = follow_button_or_trade_icon(user, auth_user)
    - elsif show_trade_icon
      = trade_icon(user, :div)

  %div(style="clear:both;")/

ruby-kid-master/app/views/users/dashboard_for_child.html.haml
.section-gap &nbsp;

= render partial: 'items/tile_item_list'
.row
  %div(class='col-xs-5 text-right')
    .user-avatar-wrapper
      .user-avatar-circle
        %a(href="#{users_edit_child_path(id: @user.id)}")
          %img.user-avatar-icon(src="#{@user.profile_image_url(:thumb)}" alt="#{@user.display_name}" title="#{@user.display_name}")
      %div(class='text-subject light-blue-color')
        %a(href="#{users_edit_child_path(id: @user.id)}") Change Picture

  .col-xs-1
  %div(class='col-xs-6' style='vertical-align: middle;')
    - if auth_user.is_a?(Parent)
      %p.text-big-title
        %a(href="#{users_edit_child_path(id: @user.id)}") Account Info
      %p.text-big-title
        %a() End Item
      %p.text-big-title
        %a() My Likes
    - else
      %p.text-big-title
        = link_to('Log Out', destroy_user_session_path)
      %p.text-big-title
        My Info
      %p.text-big-title
        Tips

- if @items
  .full-separator
  .section-gap &nbsp;

  %div(id='seller_info_box' class='row content-width center-block')
    = render(partial: 'users/seller_info', locals:{ user: @user, show_trade_icon: true, hide_user_avatar: true } )

  .section-gap &nbsp;

  %div(id='items_container' class='row content-width center-block')
    = render(partial: 'items/item_thumbnail_grid', locals:{ items: @items, favorite_counts_map: @favorite_counts, hide_user_label: true, hide_school_teacher_label: true } )

  .clearfix

- if auth_user.is_a?(Child) && auth_user.id == @user.id
  = render(partial: 'home/bottom_tabbar' )

ruby-kid-master/app/views/users/dashboard_for_parent.html.haml
%div(class='center-block content-width' style='padding-top: 40px;')
  - auth_user.children.each do|child|
    .user-avatar-wrapper
      %div(class='user-avatar-circle')
        %a(href="#{users_dashboard_path(id: child.id)}")
          %img.user-avatar-icon(src="#{child.profile_image_url(:thumb)}" alt="#{child.display_name}" title="#{child.display_name}")
      %div(class="text-user-name #{child.male? ? 'male-color' : 'female-color'}") #{child.display_name}
  .user-avatar-wrapper
    %div(class='user-avatar-circle center-block')
      %a(href="#{users_new_child_path}")
        %img(src="/assets/icons/add@2x.png" alt='Add Child' title='Add Child' class='add-user-avatar-icon vertical-center')
    %div(class='text-user-name light-blue-color')
      Add Child
%p      
%div(class='center-block content-width' style='padding-top: 40px;')
  %table(class='table')
    %tbody
      %tr
        %td
          = link_to('Browse Items', newest_items_path, class: 'text-subject dark-title-color')
      %tr
        %td
          = link_to('Account Info', edit_user_registration_path, class: 'text-subject dark-title-color')
      %tr
        %td
          = link_to('Sign Out', users_logout_path, class: 'text-subject dark-title-color')

ruby-kid-master/app/views/users/friends.html.haml
%div(class='container')

  .row
    %p.clearfix

  %table(class='content-table-width')
    %tbody
      - @friends.each do|friend|
        %tr
          %td.gray-border-color(style="border-left:0; border-right:0; border-top:0;")
            = render(partial: 'users/seller_info', locals:{ user: friend, show_trade_icon:true } )

  - if auth_user && auth_user.is_a?(Child)
    = render(partial: 'home/bottom_tabbar')

ruby-kid-master/app/views/users/reset_password.html.haml
-# @user <User> the user whose password intended to be changed.
- which_password = @user.is_a?(Child) ? "your child's password" : 'your password'
- password_label = @user.is_a?(Child) ? "Child's password" : 'Your password'
- content_for(:head_extra) do

  :css
    .login-form-group {
      padding: 30px;
      background-color: rgb(245, 245, 241);
    }
    .login-form-group button { width:80%; }
    .title-statue {
      margin-left: -115px;
    }
    img.goat { max-width: 100%; }
    @media only screen and (min-width: 641px ) and ( max-width: 840px ) {
      .title-statue {
        margin-left: -50px;
      }
      .title-statue h3 { font-size: 18pt; }
    }
    @media only screen and ( max-width: 640px )
    {
      .login-form-group {
        padding: 30px;
        border-radius: 10px;
      }
      .login-form-group button { width:100%; }
      .title-statue {
        margin-left: -25px;
      }
      .title-statue h3 { font-size: 16pt; }
      img.goat { max-width: 80%; }
    }

  :javascript
    $(function() {
      //$("#errorModal").modal({show: true } );
    });

= form_for(:user, :as => 'user', :url => session_path('user'), :html=>{:class => 'form-horizontal',  :role => 'form'}) do |f|
  .section-gap
  .container
    %div(class='login-form-group col-md-6 col-md-offset-3 col-sm-8 col-sm-2 col-sm-10 col-sm-1')
      .title-statue
        %table
          %tbody
            %tr
              %td
                %img.goat.pull-left(src='/assets/logos/goat-statue-small.png')
              %td(style="vertical-align:bottom; padding-left:5px;" )
                %h3(style="color: rgb(68, 198, 0);") Please reset #{which_password}:
      .form-group
        %h3 #{password_label}:

      %div(class='form-group')
        = f.text_field :login, :class => 'form-control large-form-field', :autofocus => true, :placeholder => "New Password"

      %div(class='form-group')
        = f.password_field :password, :class => 'form-control large-form-field', :placeholder => 'Confirm New Password'

      %div(class='form-group text-center' style='margin-top:70px;')
        %br
        = f.submit "Submit", :class => 'btn btn-primary large-form-button light-blue-bg'